# Statistic wrappers (manuscript Section 2, Table "tab:comparison")
#
# xicor(x, y) computes xi_n in the sense of "how well y is determined
# by x" -- i.e. xicor(X, Y) == xi_n(X,Y) in the manuscript's notation
# (verified empirically: xicor(X, X^2) ~ 1, xicor(X^2, X) ~ 0.26 for
# X ~ Unif(-1,1) noiseless, matching the directionality expected from
# Chatterjee 2021).

suppressPackageStartupMessages({
  library(XICOR)
  library(energy)
  library(TauStar)
})

#' All six reference statistics for one (X,Y) pair, matching Table
#' "tab:comparison" plus the applied baselines (Pearson, Spearman).
#' xi_XY = xi_n(X,Y) (how well Y is determined by X);
#' xi_YX = xi_n(Y,X) (how well X is determined by Y).
compute_statistics <- function(X, Y) {
  c(
    xi_XY    = xicor(X, Y),
    xi_YX    = xicor(Y, X),
    dcor     = dcor(X, Y),
    taustar  = tStar(X, Y),
    pearson  = cor(X, Y, method = "pearson"),
    spearman = cor(X, Y, method = "spearman"),
    hoeffd   = hoeffd_stat(X, Y)
  )
}

#' Hoeffding's D, wrapped so the rest of the code degrades gracefully
#' if Hmisc isn't installed yet (D is a complementary/diagnostic
#' measure per the manuscript's design, not the primary competitor).
hoeffd_stat <- function(X, Y) {
  if (!requireNamespace("Hmisc", quietly = TRUE)) return(NA_real_)
  Hmisc::hoeffd(X, Y)$D[1, 2]
}

#' Empirical Type I error / power: proportion of rejections at level
#' alpha across R independent (X,Y) samples generated by `gen_fun()`
#' (a zero-argument closure producing one list(X=,Y=)), for xi_n's own
#' asymptotic test (Chatterjee 2021, Thm 2.1/2.2) and, where available,
#' the permutation-based tests for dCor and tau*.
reject_rate <- function(gen_fun, R, alpha = 0.05, nperm = 199) {
  rej_xi <- rej_dcor <- rej_taustar <- logical(R)
  for (r in seq_len(R)) {
    d <- gen_fun()
    rej_xi[r]      <- xicor(d$X, d$Y, pvalue = TRUE)$pval < alpha
    rej_dcor[r]     <- dcor.test(d$X, d$Y, R = nperm)$p.value < alpha
    rej_taustar[r]  <- as.numeric(tauStarTest(d$X, d$Y, resamples = nperm)$pVal) < alpha
  }
  c(xi_n = mean(rej_xi), dcor = mean(rej_dcor), taustar = mean(rej_taustar))
}
